services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONN=postgres://user:password@db:5432/app_db?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: