name: Feature Pipeline
on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - feature/*
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Synchronize dependencies
        run: |
          go mod tidy
      - name: Download dependencies
        run: |
          go mod download
      - name: Run tests and generate JSON report
        run: |
          go test -json ./internal/core/... > test-results.json 2>&1 || true
      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Go Test Results
          path: test-results.json
          reporter: golang-json
          fail-on-error: true
          max-annotations: 10
